# Generated by Django 5.2.1 on 2025-05-22 12:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whiskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('distillery', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='api_whiskey_name_723730_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('serving_style', models.CharField(choices=[('NEAT', 'Neat'), ('ROCKS', 'On the Rocks'), ('WATER', 'With Water'), ('SODA', 'With Soda'), ('COCKTAIL', 'Cocktail')], max_length=10)),
                ('date', models.DateField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('whiskey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.whiskey')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user_id'], name='api_review_user_id_6c3434_idx'), models.Index(fields=['date'], name='api_review_date_c20cb4_idx')],
            },
        ),
    ]
