version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules
    environment:
      - HOST=0.0.0.0
      - NUXT_PUBLIC_API_BASE=http://localhost:8000
      - NUXT_PUBLIC_AWS_REGION=ap-northeast-1
      - NUXT_PUBLIC_COGNITO_USER_POOL_ID=ap-northeast-1_xxxxxxxx
      - NUXT_PUBLIC_COGNITO_CLIENT_ID=xxxxxxxxxxxxxxxxxxxxxxxxxx
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:delegated
    environment:
      - DJANGO_SECRET_KEY=django-insecure-development-key
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_S3_BUCKET=whiskey-reviews
      - AWS_ENDPOINT_URL=http://localstack:4566
      - COGNITO_USER_POOL_ID=ap-northeast-1_xxxxxxxx
      - COGNITO_CLIENT_ID=xxxxxxxxxxxxxxxxxxxxxxxxxx
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb
      - DEFAULT_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DEBUG=1
      - PERSISTENCE=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d
      - ./data/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack_data:
  frontend_node_modules: 