version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules
    environment:
      - HOST=0.0.0.0
      - NUXT_PUBLIC_API_BASE=http://localhost:8000
      - NUXT_PUBLIC_AWS_REGION=ap-northeast-1
      - NUXT_PUBLIC_COGNITO_USER_POOL_ID=ap-northeast-1_xxxxxxxx
      - NUXT_PUBLIC_COGNITO_CLIENT_ID=xxxxxxxxxxxxxxxxxxxxxxxxxx
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:delegated
    environment:
      - DJANGO_SECRET_KEY=django-insecure-development-key
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - POSTGRES_DB=whiskey
      - POSTGRES_USER=whiskey
      - POSTGRES_PASSWORD=whiskey123
      - DB_HOST=db
      - DB_PORT=5432
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_S3_BUCKET=whiskey-reviews
      - AWS_ENDPOINT_URL=http://localstack:4566
      - COGNITO_USER_POOL_ID=ap-northeast-1_xxxxxxxx
      - COGNITO_CLIENT_ID=xxxxxxxxxxxxxxxxxxxxxxxxxx
    depends_on:
      - db
      - localstack

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=whiskey
      - POSTGRES_USER=whiskey
      - POSTGRES_PASSWORD=whiskey123

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d
      - localstack_data:/var/lib/localstack

volumes:
  postgres_data:
  localstack_data:
  frontend_node_modules: 