openapi: 3.0.0
info:
  title: Whiskey Log API
  version: 2.0.0
  description: ウイスキー記録アプリのAPI仕様（サーバーレスアーキテクチャ版）
servers:
  - url: https://api.dev.whiskeybar.site
    description: Development server
  - url: https://api.whiskeybar.site
    description: Production server
security:
  - bearerAuth: []
paths:
  /api/whiskeys:
    get:
      summary: ウイスキー一覧を取得
      security: []
      tags:
        - Whiskeys
      responses:
        '200':
          description: ウイスキー一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Whiskey'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/whiskeys/search:
    get:
      summary: ウイスキーを検索（多言語対応）
      security: []
      tags:
        - Whiskeys
      parameters:
        - name: q
          in: query
          description: 検索クエリ（英語・日本語対応）
          schema:
            type: string
      responses:
        '200':
          description: 検索結果
          content:
            application/json:
              schema:
                type: object
                properties:
                  whiskeys:
                    type: array
                    items:
                      $ref: '#/components/schemas/WhiskeySearchResult'
                  count:
                    type: integer
                  query:
                    type: string
                  distillery:
                    type: string
                    description: 蒸留所フィルター（削除済み、常に空文字）
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/whiskeys/suggest:
    get:
      summary: ウイスキー名のサジェスト検索
      security: []
      tags:
        - Whiskeys
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: サジェスト結果
          content:
            application/json:
              schema:
                type: object
                properties:
                  whiskeys:
                    type: array
                    items:
                      $ref: '#/components/schemas/WhiskeySearchResult'
                  count:
                    type: integer
                  query:
                    type: string
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/whiskeys/search/suggest:
    get:
      summary: ウイスキー名のサジェスト検索（フロントエンド互換用）
      security: []
      tags:
        - Whiskeys
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: サジェスト結果
          content:
            application/json:
              schema:
                type: object
                properties:
                  whiskeys:
                    type: array
                    items:
                      $ref: '#/components/schemas/WhiskeySearchResult'
                  count:
                    type: integer
                  query:
                    type: string
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/whiskeys/ranking:
    get:
      summary: 評価が高いウイスキーのランキング取得
      security: []
      tags:
        - Whiskeys
      responses:
        '200':
          description: ランキング一覧（上位20件）
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RankingItem'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/reviews:
    get:
      summary: レビューを取得（認証ユーザーまたはパブリック）
      security:
        - bearerAuth: []
        - []
      tags:
        - Reviews
      parameters:
        - name: public
          in: query
          description: パブリックレビューを取得する場合はtrue
          schema:
            type: boolean
      responses:
        '200':
          description: レビュー一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: 新しいレビューを作成
      tags:
        - Reviews
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewInput'
      responses:
        '201':
          description: 作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/reviews/{id}:
    put:
      summary: レビューを更新
      tags:
        - Reviews
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewInput'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/reviews/public:
    get:
      summary: パブリックレビューを取得（後方互換性用）
      security: []
      tags:
        - Reviews
      responses:
        '200':
          description: パブリックレビュー一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: AWS Cognito JWT token
  responses:
    BadRequest:
      description: リクエストが不正です
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: 認証が必要です
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: アクセス権限がありません
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: リソースが見つかりません
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: サーバー内部エラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
    Whiskey:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        distillery:
          type: string
        region:
          type: string
        type:
          type: string
        created_at:
          type: string
          format: date-time
    WhiskeySearchResult:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          description: 表示用名前（日本語優先）
        name_en:
          type: string
          description: 英語名
        name_ja:
          type: string
          description: 日本語名
        distillery:
          type: string
          description: 蒸留所名（日本語優先）
        region:
          type: string
        type:
          type: string
        confidence:
          type: number
          format: float
          minimum: 0
          maximum: 1
        source:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Review:
      type: object
      properties:
        id:
          type: string
        whiskey_id:
          type: string
        whiskey_name:
          type: string
        user_id:
          type: string
        user_name:
          type: string
        notes:
          type: string
          maxLength: 2000
        rating:
          type: number
          format: float
          minimum: 1
          maximum: 5
          description: 評価（1-5）
        serving_style:
          type: string
          enum: [neat, rocks, water, highball, other]
          description: 飲み方
        date:
          type: string
          format: date
        image_url:
          type: string
          format: uri
        is_public:
          type: boolean
          default: false
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    ReviewInput:
      type: object
      required: [whiskey_id, rating, date]
      properties:
        whiskey_id:
          type: string
          description: ウイスキーID
        notes:
          type: string
          maxLength: 2000
        rating:
          type: number
          format: float
          minimum: 1
          maximum: 5
          description: 評価（1-5）
        serving_style:
          type: string
          enum: [neat, rocks, water, highball, other]
          description: 飲み方
        date:
          type: string
          format: date
        image_url:
          type: string
          format: uri
        is_public:
          type: boolean
          default: false
    RankingItem:
      type: object
      required:
        - id
        - name
        - average_rating
        - review_count
      properties:
        id:
          type: string
        name:
          type: string
        distillery:
          type: string
        region:
          type: string
        average_rating:
          type: number
          format: float
          minimum: 0
          maximum: 5
        review_count:
          type: integer
          minimum: 0
tags:
  - name: Whiskeys
    description: ウイスキー関連のエンドポイント
  - name: Reviews
    description: レビュー関連のエンドポイント