name: Deploy Whiskey App

on:
  push:
    branches:
      - main        # dev環境へのデプロイ
      - production  # prod環境へのデプロイ
  pull_request:
    branches:
      - main
      - production

env:
  NODE_VERSION: '18'

jobs:
  # 共通の設定を取得
  setup:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/production' && 'prd' || 'dev' }}
    permissions:
      id-token: write
      contents: read
    outputs:
      environment: ${{ steps.env.outputs.environment }}
      bucket_name: ${{ steps.infra.outputs.bucket_name }}
      distribution_id: ${{ steps.infra.outputs.distribution_id }}
      user_pool_id: ${{ steps.infra.outputs.user_pool_id }}
      user_pool_client_id: ${{ steps.infra.outputs.user_pool_client_id }}
      images_bucket: ${{ steps.infra.outputs.images_bucket }}
      api_repository_uri: ${{ steps.infra.outputs.api_repository_uri }}
      ecs_cluster_name: ${{ steps.infra.outputs.ecs_cluster_name }}
      ecs_service_name: ${{ steps.infra.outputs.ecs_service_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine environment
        id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
            echo "environment=prd" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi
          echo "Detected environment: ${{ github.ref }} -> $(if [[ "${{ github.ref }}" == "refs/heads/production" ]]; then echo "prd"; else echo "dev"; fi)"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
          role-session-name: GitHubActions-${{ github.run_id }}

      - name: Get infrastructure outputs
        id: infra
        run: |
          ENV=${{ steps.env.outputs.environment }}
          echo "Getting outputs for environment: $ENV"
          
          # スタック名を確認（dev->Dev, prd->Prd に変換）
          if [[ "$ENV" == "dev" ]]; then
            STACK_NAME="WhiskeyApp-Dev"
          elif [[ "$ENV" == "prd" ]]; then
            STACK_NAME="WhiskeyApp-Prd"
          else
            echo "Error: Unknown environment $ENV"
            exit 1
          fi
          echo "Stack name: $STACK_NAME"
          
          # スタックの存在を確認
          if ! aws cloudformation describe-stacks --stack-name "$STACK_NAME" >/dev/null 2>&1; then
            echo "Error: Stack $STACK_NAME not found"
            echo "Available stacks:"
            aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE UPDATE_COMPLETE --query 'StackSummaries[].StackName' --output text
            exit 1
          fi
          
          # フロントエンド用の出力取得
          BUCKET_NAME=$(aws cloudformation describe-stacks \
            --stack-name "$STACK_NAME" \
            --query "Stacks[0].Outputs[?OutputKey=='WebAppBucketName'].OutputValue" \
            --output text)
          DISTRIBUTION_ID=$(aws cloudformation describe-stacks \
            --stack-name "$STACK_NAME" \
            --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" \
            --output text)
          USER_POOL_ID=$(aws cloudformation describe-stacks \
            --stack-name "$STACK_NAME" \
            --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" \
            --output text)
          USER_POOL_CLIENT_ID=$(aws cloudformation describe-stacks \
            --stack-name "$STACK_NAME" \
            --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" \
            --output text)
          IMAGES_BUCKET=$(aws cloudformation describe-stacks \
            --stack-name "$STACK_NAME" \
            --query "Stacks[0].Outputs[?OutputKey=='ImagesBucketName'].OutputValue" \
            --output text)
          
          # API用の出力取得
          API_REPOSITORY_URI=$(aws cloudformation describe-stacks \
            --stack-name "$STACK_NAME" \
            --query "Stacks[0].Outputs[?OutputKey=='ApiRepositoryUri'].OutputValue" \
            --output text)
          ECS_CLUSTER_NAME=$(aws cloudformation describe-stacks \
            --stack-name "$STACK_NAME" \
            --query "Stacks[0].Outputs[?OutputKey=='EcsClusterName'].OutputValue" \
            --output text)
          ECS_SERVICE_NAME=$(aws cloudformation describe-stacks \
            --stack-name "$STACK_NAME" \
            --query "Stacks[0].Outputs[?OutputKey=='EcsServiceName'].OutputValue" \
            --output text)
          
          echo "Retrieved values:"
          echo "Bucket: $BUCKET_NAME"
          echo "Distribution: $DISTRIBUTION_ID"
          echo "User Pool: $USER_POOL_ID"
          echo "Client ID: $USER_POOL_CLIENT_ID"
          echo "Images Bucket: $IMAGES_BUCKET"
          echo "API Repository URI: $API_REPOSITORY_URI"
          echo "ECS Cluster: $ECS_CLUSTER_NAME"
          echo "ECS Service: $ECS_SERVICE_NAME"
          
          if [[ -z "$BUCKET_NAME" || "$BUCKET_NAME" == "None" ]]; then
            echo "Error: Could not retrieve bucket name"
            exit 1
          fi
          
          echo "bucket_name=$BUCKET_NAME" >> $GITHUB_OUTPUT
          echo "distribution_id=$DISTRIBUTION_ID" >> $GITHUB_OUTPUT
          echo "user_pool_id=$USER_POOL_ID" >> $GITHUB_OUTPUT
          echo "user_pool_client_id=$USER_POOL_CLIENT_ID" >> $GITHUB_OUTPUT
          echo "images_bucket=$IMAGES_BUCKET" >> $GITHUB_OUTPUT
          echo "api_repository_uri=$API_REPOSITORY_URI" >> $GITHUB_OUTPUT
          echo "ecs_cluster_name=$ECS_CLUSTER_NAME" >> $GITHUB_OUTPUT
          echo "ecs_service_name=$ECS_SERVICE_NAME" >> $GITHUB_OUTPUT

  # フロントエンドデプロイ
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: setup
    environment: ${{ github.ref == 'refs/heads/production' && 'prd' || 'dev' }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
          role-session-name: GitHubActions-Frontend-${{ github.run_id }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: frontend/package.json

      - name: Install frontend dependencies
        run: |
          cd frontend
          echo "Installing dependencies..."
          npm install
          echo "Dependencies installed successfully"

      - name: Create environment file
        run: |
          cd frontend
          echo "Creating environment file for ${{ needs.setup.outputs.environment }} environment..."
          cat > .env << EOF
          NUXT_PUBLIC_USER_POOL_ID=${{ needs.setup.outputs.user_pool_id }}
          NUXT_PUBLIC_USER_POOL_CLIENT_ID=${{ needs.setup.outputs.user_pool_client_id }}
          NUXT_PUBLIC_REGION=ap-northeast-1
          NUXT_PUBLIC_IMAGES_BUCKET=${{ needs.setup.outputs.images_bucket }}
          NUXT_PUBLIC_API_BASE_URL=${{ needs.setup.outputs.environment == 'prd' && 'https://api.whiskeybar.site' || 'https://api.dev.whiskeybar.site' }}
          NUXT_PUBLIC_ENVIRONMENT=${{ needs.setup.outputs.environment }}
          EOF
          echo "Environment file created:"
          cat .env

      - name: Build Nuxt.js application
        run: |
          cd frontend
          echo "Building Nuxt.js application for static hosting..."
          npm run generate
          echo "Build completed successfully"
          echo "Output directory contents:"
          ls -la .output/ || echo "Output directory not found"
          ls -la .output/public/ || echo "Public directory not found"

      - name: Deploy to S3
        run: |
          cd frontend
          echo "Deploying to S3 bucket: ${{ needs.setup.outputs.bucket_name }}"
          aws s3 sync .output/public/ s3://${{ needs.setup.outputs.bucket_name }}/ --delete
          echo "S3 deployment completed"

      - name: Invalidate CloudFront
        run: |
          echo "Invalidating CloudFront distribution: ${{ needs.setup.outputs.distribution_id }}"
          aws cloudfront create-invalidation \
            --distribution-id ${{ needs.setup.outputs.distribution_id }} \
            --paths "/*"
          echo "CloudFront invalidation completed"

  # APIデプロイ
  deploy-api:
    runs-on: ubuntu-latest
    needs: setup
    environment: ${{ github.ref == 'refs/heads/production' && 'prd' || 'dev' }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
          role-session-name: GitHubActions-API-${{ github.run_id }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          cd backend
          echo "Building Docker image for API..."
          
          # Extract repository name from URI
          REPOSITORY_URI=${{ needs.setup.outputs.api_repository_uri }}
          IMAGE_TAG="${{ github.sha }}"
          
          echo "Repository URI: $REPOSITORY_URI"
          echo "Image Tag: $IMAGE_TAG"
          
          # Build image
          docker build -t $REPOSITORY_URI:$IMAGE_TAG .
          docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
          
          # Push image
          echo "Pushing image to ECR..."
          docker push $REPOSITORY_URI:$IMAGE_TAG
          docker push $REPOSITORY_URI:latest
          
          echo "Docker image pushed successfully"
          echo "image_uri=$REPOSITORY_URI:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Update ECS service
        run: |
          echo "Updating ECS service..."
          
          CLUSTER_NAME=${{ needs.setup.outputs.ecs_cluster_name }}
          SERVICE_NAME=${{ needs.setup.outputs.ecs_service_name }}
          
          echo "Cluster: $CLUSTER_NAME"
          echo "Service: $SERVICE_NAME"
          
          # Force new deployment
          aws ecs update-service \
            --cluster $CLUSTER_NAME \
            --service $SERVICE_NAME \
            --force-new-deployment
          
          echo "ECS service update initiated"
          
          # Wait for deployment to complete
          echo "Waiting for deployment to stabilize..."
          aws ecs wait services-stable \
            --cluster $CLUSTER_NAME \
            --services $SERVICE_NAME
          
          echo "ECS deployment completed successfully"

  # デプロイ完了通知
  notify:
    runs-on: ubuntu-latest
    needs: [setup, deploy-frontend, deploy-api]
    if: always()

    steps:
      - name: Notify deployment status
        run: |
          FRONTEND_STATUS="${{ needs.deploy-frontend.result }}"
          API_STATUS="${{ needs.deploy-api.result }}"
          ENV="${{ needs.setup.outputs.environment }}"
          
          echo "=== Deployment Summary ==="
          echo "Environment: $ENV"
          echo "Frontend Status: $FRONTEND_STATUS"
          echo "API Status: $API_STATUS"
          
          if [[ "$FRONTEND_STATUS" == "success" && "$API_STATUS" == "success" ]]; then
            echo "✅ Full deployment to $ENV environment successful!"
          elif [[ "$FRONTEND_STATUS" == "success" ]]; then
            echo "⚠️ Frontend deployment successful, but API deployment failed"
          elif [[ "$API_STATUS" == "success" ]]; then
            echo "⚠️ API deployment successful, but frontend deployment failed"
          else
            echo "❌ Both frontend and API deployments failed"
          fi 